# 参考URL: https://qiita.com/ucan-lab/items/56c9dc3cf2e6762672f4

# docker-compose定義ファイルのバージョン
version: "3"

# サービスの定義
services:
  app-php:  # コンテナ名が app-php
    build:  # Dockerイメージをbuildするための設定
      context: ./docker/php # Dockerfile などビルド設定があるディレクトリ名
      args: # ビルド時に渡す引数、--build-arg で指定するのと同じ
        - TZ=${TZ}
    volumes:  # コンテナにマウントするときの設定
      - ./src:/work # ホスト側（PC本体側）のパス:コンテナ側のパス
      - ./logs:/var/log/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /work  # Dockerfileで定義した命令を実行するための作業用ディレクトリ
    environment:  # コンテナ内の環境変数
      - DB_CONNECTION=mysql
      - DB_HOST=db-mysql
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - TZ=${TZ}
  server-nginx:
    image: nginx:1.23.3-alpine
    depends_on:
      - app-php
    # ホストでポート`8080`をdocker上では`80`にする
    ports:
      - 8080:80
    volumes:
      - ./src:/work
      - ./logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=${TZ}
  db-mysql:
    image: mysql:8.0
    ports:
      - 13306:3306
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}

# ボリュームの定義
volumes:
  db-store: